### ISSUE TITLE
1.0.0-alpha.1 crashes

### ISSUE THREAD

**Issue by MarioFlying** [linimin/lbry-androidtv#2]
Hi, in my regular checks for ways to watch lbry/Odysee on my TVs, I just saw the alpha was out and tried it out right away.
For now, it shows the splash screen for half a second then crashes.
Still happy to see things happening.

Fire TV Stick lite

**Comment by linimin** [comment]
This app also needs some modifications to support Fire TV properly, this will be included in the next version.

**Comment by MarioFlying** [comment]
> this will be included in the next version.

Looking forward to it

**Comment by nor-ric** [comment]
Hello, thanks for starting this project.
I'm currently experiencing the same behaviour as above: crash after half a second displaying the splash screen.
This is on a standard AndroidTV 8, with google play services.
Here is the logcat:

> FATAL EXCEPTION: main
Process: app.newproj.lbrytv, PID: 5972
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.newproj.lbrytv/app.newproj.lbrytv.TvActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class androidx.leanback.widget.VerticalGridView

**Comment by linimin** [comment]
This issue has been fixed in [v1.0.0-alpha.2](https://github.com/linimin/lbry-androidtv/releases/tag/v1.0.0-alpha.2).

**Comment by nor-ric** [comment]
Confirmed!

**Comment by MarioFlying** [comment]
Confirmed, the issue is fixed
