### ISSUE TITLE
Screensaver is not deactivated

### ISSUE THREAD

**Issue by MarioFlying** [linimin/lbry-androidtv#3]
On the Amazon Fire TV Stick lite, video playback should stop the screensaver set countdown timer.
Instead, the screensaver stays active and launches anyway, interrupting video playback; once the screensaver has been halted by pushing a key on the remote, the video fails to resume playing and must be stopped and re-opened again.

Alpha 5

**Comment by linimin** [comment]
Thanks for reporting this, it should be fixed in [v1.0.0-alpha.6](https://github.com/linimin/lbry-androidtv/releases/tag/v1.0.0-alpha.6).

**Comment by MarioFlying** [comment]
> it should be fixed in [v1.0.0-alpha.6]

And it's been fixed in alpha 6, indeed 👍🏻
