### ISSUE TITLE
Incompatible with Chromecast with Google TV

### ISSUE THREAD

**Issue by djbacon** [linimin/lbry-androidtv#6]
I just found out about this projects and I'm excited to finally watch LBRY content on my tv, but when I open it on Play Store it tells me "This app is not available for any of your devices". I have Chromecast with Google TV that should be compatible. Is it a bug or it really is not compatible yet?

**Comment by linimin** [comment]
Thank your for your interest in this project! Unfortunately, I just found that I need to make this app pass Google's Android TV quality review before it can be searched and installed from the store. The review is in progress, once passed, it should be able to install on your Chromecast.

**Comment by djbacon** [comment]
Thank you.
