### ISSUE TITLE
Login using Email Link doesn't work.

### ISSUE THREAD

**Issue by djbacon** [linimin/lbry-androidtv#7]
I installed on my Chromecast for Google TV. Wanted to login so I open Settings and select Swith Account. Then I enter my email, choose Email Link and select Continue.
I receive email containing login link and click on it on my PC (Ubuntu 20.04, Brave [Version 1.37.116 Chromium: 100.0.4896.127]) and it shows 
```
Log in
Welcome back! You are automatically being signed in.
```
The screen on LBRY.tv app keeps showing text to click on link on email I received. I waited almost a minute after clicking on login link, but it did not log me in. I did it twice and same result.

One weird thing. First time after it did not work, I refreshed the page of login link and after few seconds it showed error something about captcha was not correct or something. It was very brief. Maybe it helps.

**Comment by linimin** [comment]
Thanks for reporting this, would you mind to test it again?
